<a href="https://colab.research.google.com/github/np03cs4s250092-commits/5CS037/blob/master/Rejina_Rana_Magar_Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#Problem 1 Array Creation:
#Initialize an empty array with size 2*2
import numpy as np
arr = np.zeros((2, 2))   # creates a 2x2 array filled with 0s
print(arr)



[[0. 0.]
 [0. 0.]]


In [4]:
#Initialize an all one array with size 4X2.
import numpy as np

arr = np.ones((4, 2))
print(arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np

arr = np.full((3, 3), 4)
print(arr)


[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [12]:
#Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.zeros_like(a)

print(b)






[[0 0 0]
 [0 0 0]]


In [15]:
# Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
import numpy as np

a = np.array([[4, 8, 12],
              [16, 20, 24]])

b = np.ones_like(a)

print(b)



[[1 1 1]
 [1 1 1]]


In [17]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np

new_list = [1, 2, 3, 4]

arr = np.array(new_list)

print(arr)


[1 2 3 4]


In [19]:
#problem2:Array Manipulation: Numerical Ranges and Array indexing:
#1 Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [21]:
#2 Create a 3X3 matrix with values ranging from 0 to 8.
#{Hint:look for np.reshape()}
import numpy as np
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
#3 Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#4. Create a random array of size 30 and find the mean of the array.
#{Hint:check for np.random.random() and array.mean() function}
import numpy as np
arr=np.random.random(30)
mean=arr.mean()
print(mean)

0.5619824558516836


In [27]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.

import numpy as np
arr=np.random.random((10,10))
min_value=arr.min()
max_value=arr.max()
print(min_value)

0.003641704915027133


In [29]:
#6. Create a zero array of size 10 and replace 5th element with 1.

import numpy as np
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
#7. Reverse an array arr = [1,2,0,0,4,0].

import numpy as np
arr=np.array([1,2,0,0,4,0])
reversed_arr=arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [33]:
#8. Create a 2d array with 1 on border and 0 inside.

import numpy as np
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [41]:
#Problem - 3: Array Operations:
"""For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
"""
#1 Add the two array.
import numpy as np
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
sum=x+y
print(sum)

[[ 6  8]
 [10 13]]


In [43]:
#2. Subtract the two array.
import numpy as np
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
sub=x-y
print(sub)


[[-4 -4]
 [-4 -3]]


In [45]:
#3. Multiply the array with any integers of your choice.
import numpy as np
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
mul=x*y
print(mul)

[[ 5 12]
 [21 40]]


In [47]:
#4. Find the square of each element of the array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
square_arr = np.square(arr)
print(square_arr)

[ 1  4  9 16 25]


In [57]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
import numpy as np
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
x = np.array([7, 8, 9])
y = np.array([10, 11, 12])
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)


Dot product of v and w: 32
Dot product of x and v: 50
Dot product of x and y: 266


In [72]:
#6Concatenate x(and)y along row and Concatenate v(and)w along column.
#{Hint:try np.concatenate() or np.vstack() functions.
xy_row = np.concatenate((x, y), axis=0)
print(xy_row)
vw_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
print(vw_col)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[11 14]
 [12 15]
 [13 16]]


In [75]:
#7
np.concatenate((x, v))
"""We get an error because x is a 2D array and v is a 1D array, so their shapes don’t match. NumPy can only join arrays that have the same kind of shape. Since one has rows and columns and the other doesn’t, NumPy doesn’t know how to combine them, so it shows an error."""

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [77]:
"""Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:"""
#1. Prove A.A−1 = I.
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
print(A.dot(np.linalg.inv(A)))


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [79]:
#2. Prove AB ̸= BA.
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAre AB and BA equal? ->", np.array_equal(AB, BA))




AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Are AB and BA equal? -> False


In [81]:
# 3. Prove (AB)^T = B^T * A^T
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T:\n", AB_T)
print("\nB^T A^T:\n", BT_AT)
print("\nIs (AB)^T equal to B^T A^T? ->", np.array_equal(AB_T, BT_AT))



(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T? -> True


In [83]:
# 4. Solve the system of equations using inverse method
# System:
# 2x − 3y +  z = −1
#  x −  y + 2z = −3
# 3x +  y −  z =  9

# Matrix form AX = B

A_eq = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3,  1, -1]
])

B_eq = np.array([-1, -3, 9])

# Solve using inverse: X = A^-1 * B
A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)

print("\nSolution using inverse method (x, y, z):\n", X)


Solution using inverse method (x, y, z):
 [ 2.  1. -2.]


In [1]:
# Also solve using numpy built-in solver for verification
X_verify = np.linalg.solve(A_eq, B_eq)

print("\nSolution using np.linalg.solve:\n", X_verify)

NameError: name 'np' is not defined

In [2]:
import numpy as np
import time

#ADDITION
# Python lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")
# NumPy arrays
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")

#MULTIPLICATION
# Python lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")
# NumPy arrays
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")

#DOT PRODUCT
# Python lists
start = time.time()
dot_py = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")
# NumPy arrays
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start, "seconds")

#MATRIX MULTIPLICATION
# Python lists
M1 = [[i for i in range(1000)] for _ in range(1000)]
M2 = [[i for i in range(1000)] for _ in range(1000)]
start = time.time()
# matrix multiplication using python
result_py = [[sum(M1[i][k] * M2[k][j] for k in range(1000))
              for j in range(1000)]
              for i in range(1000)]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")

# NumPy arrays
A = np.arange(1_000_000).reshape(1000, 1000)
B = np.arange(1_000_000).reshape(1000, 1000)
start = time.time()
result_np = np.dot(A, B)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start, "seconds")

Python List Addition Time: 0.24041104316711426 seconds
NumPy Array Addition Time: 0.0063130855560302734 seconds
Python List Multiplication Time: 0.21523809432983398 seconds
NumPy Array Multiplication Time: 0.0051763057708740234 seconds
Python List Dot Product Time: 0.20937800407409668 seconds
NumPy Dot Product Time: 0.002524137496948242 seconds
Python List Matrix Multiplication Time: 190.29364490509033 seconds
NumPy Matrix Multiplication Time: 2.1172542572021484 seconds
